### ISSUE TITLE
assorted comments on notesclub

### ISSUE THREAD

**Issue by RichMorin** [notesclub/notesclub#152]
I recently started a thread on ElixirForum ([Where (and how) should “public” Livebooks be archived?](https://elixirforum.com/t/where-and-how-should-public-livebooks-be-archived/54816)). Following up on a response by @hugobarauna, I visited notesclub. Here are some assorted comments...

First, I'm very pleased that notesclub was created. It seems like a great start on indexing Livebooks; as time goes on, it should get even better. +1

I have no idea how many Livebooks are currently indexed by notesclub, but it's clearly a large number which can be expected to grow substantially over time. (It would be nice to have this number displayed somewhere. :-)

When @josevalim did a GitHub search on the `*.livemd` pattern, he got ~5K hits. Trying to find particular kinds of Livebooks is already challenging and will get even harder over time. So, I'd like to see more support for filtering, "advanced" searches, etc.

Once a Livebook has been identified, it would be useful to collect a bit more metadata. For instance, a list of direct dependencies could be harvested from the initial `Mix.install` calls. Download counts (as presented in hex.pm) might also help folks decide which Livebooks to investigate.

On a related note, notesclub could encourage creators to "tag" their Livebooks in some manner.  These tags (e.g., AI, database, graphics, Nerves) could also be used for filtering, searching, etc. Getting creators to begin Livebooks with a quotable "subject line" would also be helpful.

-r

**Comment by hectorperez** [comment]
Hi Rich, thanks for your message!

We have 5806 notebooks, and we add new ones every day.
The number is at the bottom, but since we added an infinite scroll, it's only displayed when you go to a user or repo page.
E.g. https://notes.club/livebook-dev (go to the bottom)
We should display it somewhere else. Any idea about where/how should it be displayed?

We have an [issue](https://github.com/notesclub/notesclub/issues/4) to extract mix packages.
It would be great to display them as tags and be able to see all notebooks with a package.
By the way, what other metadata are you interested in?

Great idea about the tags! Maybe it could be done automatically with some AI 🤔  And/or manually. After the [log in with GitHub issue](https://github.com/notesclub/notesclub/issues/127), we could let authors tag their notebooks. And maybe let people tag other people's notebooks — not sure.

Cheers!

**Comment by hectorperez** [comment]
The notebook count is at the top now. Thanks! :)
https://github.com/notesclub/notesclub/pull/155

**Comment by RichMorin** [comment]
Thanks for re-positioning the notebook count. By the way, the count has dropped to "3809 notebooks and counting". Wazzup?

# Categories and Tags

I just added a comment and suggestion [here](https://github.com/livebook-dev/livebook/discussions/1843#discussioncomment-6470708). Feel free to jump into the discussion.

# Discoverability, documentation, etc.

The notesclub UI is rather opaque: I can enter text into the search field and get results, but I have no real understanding of how the search works. I'm guessing that it's a fairly simple text-based search, but if I knew more about how it worked, I might be able to make better use of it. So, an overview page of some sort would be a great addition.

Similarly, it appears that notesclub also has an API of sorts, allowing users to add query strings to the URL. However, I don't see anything on the page that describes the allowable syntax.  Again, an overview page would help.

# Advanced search mode(s)

Some web sites provide advanced search mode(s) which can be very useful in reducing false positives, etc. For example, they might let the user specify logical combinations of categories, keywords, tags, etc. Another possibility would be to let users specify update activity and/or date ranges, to avoid abandoned and dated contributions.

As the count of published Livebooks goes up, making fine distinctions in queries will become more and more useful. Please consider adding support for this.

-r

**Comment by hectorperez** [comment]
@RichMorin I missed your last comment, sorry!!

# Count
I think the drop in notebooks was because we were not deleting renamed/deleted notebooks until https://github.com/notesclub/notesclub/pull/160

# Search
As you commented, the current search is basic. You can see the code [here](https://github.com/notesclub/notesclub/blob/main/lib/notesclub_web/live/notebook_live/index.ex#L209) and [here](https://github.com/notesclub/notesclub/blob/main/lib/notesclub/notebooks.ex#L66).

When we search, we do these two searches (and concatenate them):
1. We search `notebook.title`, `notebook.github_filename`, `user.name`, `notebook.github_owner_login`, `notebook.github_repo_name`.
2. We search `notebook.content`.

# Advanced Search
An advanced search mode is a great idea. As a first step, we could have categories or tags created automatically 🤔 


# URLs
https://notes.club/josevalim (user)
https://notes.club/josevalim/livebooks (repo)
https://notes.club/hex/kino (hex package)
https://notes.club/search?q=axon (search)

Do you mean this? If so, where could we document this? In the readme? Or on a page on the website?

**Comment by hectorperez** [comment]
Closing this. If you have any other question, please reopen. Thanks!
